name: simple_wiki_arctic
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit
    - "snowflake-snowpark-python[pandas]==1.5.1"
    - requests
    - torch
    - datasets
    - sentence-transformers==2.2.2
    - ipython
    - "fastapi[all]"
    - -r requirements.txt
    # - wikitextparser

