USE DATABASE CONTAINERS_DB;
USE SCHEMA CONTAINERS_DB.SIMPLE_WIKI_SEARCH;
USE WAREHOUSE SIMPLE_WIKI_WH;

CREATE STAGE IF NOT EXISTS specs ENCRYPTION = (TYPE='SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS models ENCRYPTION = (TYPE='SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS data ENCRYPTION = (TYPE='SNOWFLAKE_SSE');
CREATE IMAGE REPOSITORY IF NOT EXISTS images;
// get the repository_url and add it to .env
// also, login in the console:
// docker login repository_url -u containers_user
SHOW IMAGE REPOSITORIES IN SCHEMA CONTAINERS_DB.SIMPLE_WIKI_SEARCH;
// docker compose build
// docker compose push simple-wiki-jupyter-sf
DESCRIBE COMPUTE POOL SIMPLE_WIKI_POOL_XS;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_XS SUSPEND;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_XS RESUME;
DESCRIBE COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S SUSPEND;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S RESUME;

DESCRIBE COMPUTE POOL SIMPLE_WIKI_POOL_GPU_M;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_GPU_M SUSPEND;
-- ALTER COMPUTE POOL SIMPLE_WIKI_POOL_GPU_M RESUME;

EXECUTE SERVICE
  IN COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S
  FROM @specs
  SPEC='simple-wiki-job.yaml'
EXTERNAL_ACCESS_INTEGRATIONS = (SIMPLE_WIKI_ACCESS_INTEGRATION)
;

-- SET jobid = LAST_QUERY_ID();
-- or get manually and set this variable
SET jobid='01b3dde1-0302-a16a-0001-6f86008b62be';
SELECT SYSTEM$GET_JOB_STATUS($jobid);

SELECT SYSTEM$GET_JOB_LOGS($jobid, 'main', 10);
