// RUN WITH ROLE THAT CAN USE ACCOUNTADMIN AND USERADMIN
// let's setup the environment
// first user and database
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS CONTAINERS_ROLE;
CREATE USER IF NOT EXISTS CONTAINERS_USER
PASSWORD='PUT YOUR SECR3T P488W0RD HER3!'
DEFAULT_ROLE = CONTAINERS_ROLE
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE CONTAINERS_ROLE TO USER CONTAINERS_USER;
GRANT ROLE CONTAINERS_ROLE TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS CONTAINERS_DB;
GRANT ALL PRIVILEGES ON DATABASE CONTAINERS_DB TO ROLE CONTAINERS_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA CONTAINERS_DB.PUBLIC TO ROLE CONTAINERS_ROLE;

CREATE SCHEMA IF NOT EXISTS CONTAINERS_DB.SIMPLE_WIKI_SEARCH;
GRANT ALL PRIVILEGES ON SCHEMA CONTAINERS_DB.SIMPLE_WIKI_SEARCH TO ROLE CONTAINERS_ROLE;

CREATE OR REPLACE WAREHOUSE SIMPLE_WIKI_WH WITH WAREHOUSE_SIZE='X-SMALL';

GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE SIMPLE_WIKI_WH TO ROLE CONTAINERS_ROLE;
