// RUN WITH ROLE THAT CAN USE ACCOUNTADMIN AND USERADMIN
// Let us setup container environment
USE ROLE ACCOUNTADMIN;
CREATE SECURITY INTEGRATION IF NOT EXISTS SNOWSERVICES_INGRESS_OAUTH_SIMPLE_WIKI
  TYPE=OAUTH
  OAUTH_CLIENT=SNOWSERVICES_INGRESS
  ENABLED=TRUE;

GRANT OWNERSHIP ON INTEGRATION SNOWSERVICES_INGRESS_OAUTH_SIMPLE_WIKI
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;


CREATE OR REPLACE NETWORK RULE SIMPLE_WIKI_NETWORK_RULE
MODE = EGRESS
TYPE = HOST_PORT
VALUE_LIST = ('0.0.0.0:443'. '0.0.0.0:80''); -- allow access to the whole internet on port 443 and 80
GRANT OWNERSHIP ON NETWORK RULE SIMPLE_WIKI_NETWORK_RULE
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;


CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SIMPLE_WIKI_ACCESS_INTEGRATION
ALLOWED_NETWORK_RULES = (SIMPLE_WIKI_NETWORK_RULE)
ENABLED = TRUE;
GRANT OWNERSHIP ON INTEGRATION SIMPLE_WIKI_ACCESS_INTEGRATION
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;




// now, let us create compute pools
-- DROP COMPUTE POOL SIMPLE_WIKI_POOL_XS;
CREATE COMPUTE POOL IF NOT EXISTS SIMPLE_WIKI_POOL_XS
MIN_NODES = 1
MAX_NODES = 4
INSTANCE_FAMILY = STANDARD_1;
GRANT OWNERSHIP ON COMPUTE POOL SIMPLE_WIKI_POOL_XS
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;


-- DROP COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S;
CREATE COMPUTE POOL IF NOT EXISTS SIMPLE_WIKI_POOL_GPU_S
MIN_NODES = 1
MAX_NODES = 4
INSTANCE_FAMILY = GPU_NV_S;
GRANT OWNERSHIP ON COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;


-- DROP COMPUTE POOL SIMPLE_WIKI_POOL_GPU_S;
CREATE COMPUTE POOL IF NOT EXISTS SIMPLE_WIKI_POOL_GPU_M
MIN_NODES = 1
MAX_NODES = 4
INSTANCE_FAMILY = GPU_NV_M;
GRANT OWNERSHIP ON COMPUTE POOL SIMPLE_WIKI_POOL_GPU_M
TO ROLE CONTAINERS_ROLE REVOKE CURRENT GRANTS;